package com.jdbcStarter;


import com.jdbcStarter.util.ConnectionManager;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class JdbcRunner {

    public static void main(String[] args) throws SQLException {

        String sql1 = """
                INSERT INTO info (data)
                VALUES ('autogenerated'), ('data');
                """;

        try (Connection connection = ConnectionManager.open();
             Statement statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE)) {//Обернуто в try with resources.

            int executeResult = statement.executeUpdate(sql1, Statement.RETURN_GENERATED_KEYS); //ResultSet можно не оборачивать в try with resources, т.к. закроетса автоматически сразу как закроется statement.
            ResultSet generatedKeys = statement.getGeneratedKeys();
            while (generatedKeys.next()) {
                int generatedId = generatedKeys.getInt("id");
                String generatedData = generatedKeys.getString("data");
                System.out.println(String.format("id: %d, data: %s", generatedId, generatedData));
            }
        }
    }
}

